name: Scheduled build

on:
  schedule:
    # 毎週日曜03:01にビルド(UTCで18:01)
    - cron: '01 18 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Vercel Deploy
        run: |
          curl --request POST \
          --url "${{ secrets.BUILD_HOOK_URL }}"
